version: '3.4'
services:
  web:
    build:
      context: ./web
      target: build-stage
    ports:
      - "8080:8080"
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ".:/workspace/tracker"
  influxdb:
    image: influxdb
    volumes:
      - "./influxdb:/var/lib/influxdb"
    ports:
      - "8086:8086"
  chronograf:
    image: chronograf
    volumes:
      - "./chronograf:/var/lib/chronograf"
    ports:
      - "8888:8888"
